# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

 
services:

  magictserver:
    image: magictserver
    container_name: magictserver
    build:
      context: .
      dockerfile: MagicT.Server/Dockerfile
    ports:
      - 5029:80
    depends_on:
      - azuresqledge
      - redis
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5029"]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MagicTContext=Server=azuresqledge,1433;Database=MagicTContext;User Id=sa;Password=LucidNala88!;TrustServerCertificate=true
      - MagicTRedisConfig__ConnectionString=redis:6379
      - Kestrel__EndpointDefaults__Protocols=Http2
      - Certificate__CrtPath=/app/server.crt
      - Certificate__KeyPath=/app/server.key
    volumes:
      - servervolume:/MagicT.Server:/app

  magictswaggerserver:
    image: magictswaggerserver
    container_name: magictswaggerserver
    build:
      context: .
      dockerfile: MagicT.Server/Dockerfile
    ports:
      - 5028:80
    depends_on:
      - azuresqledge
      - redis
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5029"]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MagicTContext=Server=azuresqledge,1433;Database=MagicTContext;User Id=sa;Password=LucidNala88!;TrustServerCertificate=true
      - MagicTRedisConfig__ConnectionString=redis:6379
      - Kestrel__EndpointDefaults__Protocols=Http1
  magictweb:
    image: magictweb
    container_name: magictweb
    build:
      context: .
      dockerfile: MagicT.Web/Dockerfile
    ports:
      - 5084:80  
    depends_on:
      - magictserver  
    networks:
      - mynetwork
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MagicTRedisConfig__ConnectionString=redis:6379
      - API_BASE_URL__HTTP=http://magictserver
      - API_BASE_URL__HTTPS=https://magictserver

  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - redisvolume:/data
    ports:
      - "6379:6379"
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always

  azuresqledge:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: azuresqledge
    volumes:
      - sqlvolume:/var/opt/mssql
    environment:
      - ACCEPT_EULA=1
      - MSSQL_SA_PASSWORD=LucidNala88!
    ports:
      - 1433:1433
    cap_add:
      - SYS_PTRACE
    networks:
      - mynetwork
    healthcheck:
      test:
        - CMD
        - curl
        - --fail
        - http://localhost:1433
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always


volumes:
  sqlvolume: null
  redisvolume: null
  servervolume: null

networks:
  mynetwork:
    driver: bridge